services:
 db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: example
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodbdata:/data/db
    ports:
      - 27017:27017
 
volumes:
  mongodbdata: